tap "jez/formulae"
tap "thoughtbot/formulae"
tap "homebrew/science"
tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/versions"
tap "caskroom/cask"
cask "java"
brew "archey"
brew "gcc"
brew "awk"
brew "bash"
brew "ccat"
brew "cloc"
brew "cmake"
brew "ghostscript"
brew "ffmpeg"
brew "gifsicle"
brew "gist"
brew "git"
brew "gnuplot", args: ["with-cairo"]
brew "go"
brew "python"
brew "grc"
brew "heroku"
brew "htop"
brew "imagemagick"
brew "jp2a"
brew "make"
brew "mas"
brew "qpdf"
brew "ocrmypdf"
brew "octave"
brew "pandoc"
brew "pandoc-citeproc"
brew "pandoc-crossref"
brew "potrace"
brew "q"
brew "r"
brew "thefuck"
brew "tig"
brew "tmux"
brew "tree"
brew "unrar"
brew "vim"
brew "watch"
brew "wget"
brew "z"
brew "jez/formulae/pandoc-sidenote"
brew "thoughtbot/formulae/gitsh"
cask "aerial"
cask "apptrap"
cask "basictex"
cask "beamer"
cask "bowtie"
cask "caffeine"
cask "coconutbattery"
cask "dropbox"
cask "iina"
cask "imageoptim"
cask "intellij-idea-ce"
cask "iterm2"
cask "itsycal"
cask "keybase"
cask "paste"
cask "real-vnc"
cask "sequel-pro"
cask "signal"
cask "skype"
cask "sublime-text"
cask "transmission"
cask "vanilla"
mas "1Password", id: 443987910
mas "Encrypto", id: 935235287
mas "Evernote", id: 406056744
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Telegram", id: 747648890
mas "Things3", id: 904280696
mas "Tweetbot", id: 557168941
mas "Xcode", id: 497799835
